name: Build

on:
    push:
      branches: [main, master]
    pull_request:
      types: [opened, synchronize]

defaults:
  run:
    shell: bash

jobs:
  build-wasm:
    name: WebAssembly (WASI) Build
    runs-on: ubuntu-22.04

    env:
      WASI_VERSION: 25
      WASI_VERSION_FULL: 25.0
      WASI_SDK_DIR: ${{ github.workspace }}/wasi-sdk
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download wasi-sdk
        run: |
          curl -L https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${{env.WASI_VERSION}}/wasi-sdk-${{env.WASI_VERSION_FULL}}-x86_64-linux.tar.gz | tar xz
          mv wasi-sdk-${{env.WASI_VERSION}} wasi-sdk

      - name: Configure project
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=${WASI_SDK_DIR}/share/cmake/wasi-sdk.cmake \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: |
          cd build
          cmake --build .

      - name: Upload WebAssembly artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-artifacts
          path: |
            build/**/*.wasm

  linux-build:
    name: Linux build

    runs-on: ubuntu-22.04

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Dependencies (x86)
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y build-essential g++-multilib libc6-dev:i386

      - name: Configure & build
        run: |
          mkdir out
          cd out
          cmake ..
          make

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path:  out/bin/**
          retention-days: 7
