name: Build

on:
    push:
      branches: [main, master]
    pull_request:
      types: [opened, synchronize]

defaults:
  run:
    shell: bash

jobs:
  build-wasm:
    name: WebAssembly (WASI) Build
    runs-on: ubuntu-22.04
    if: false # Disable this job because WASI do not support setjmp/longjmp
    env:
      WASI_VERSION: "25"
      WASI_VERSION_FULL: "25.0"
      WASI_SDK_DIR: ${{ github.workspace }}/wasi-sdk
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download wasi-sdk
        run: |
          curl -L https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${{env.WASI_VERSION}}/wasi-sdk-${{env.WASI_VERSION_FULL}}-x86_64-linux.tar.gz | tar xz
          ls -lah
          mv wasi-sdk-${{env.WASI_VERSION_FULL}}-x86_64-linux wasi-sdk

      - name: Configure project
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=${{env.WASI_SDK_DIR}}/share/cmake/wasi-sdk.cmake \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: |
          cd build
          cmake --build .
          find .

      - name: Upload WebAssembly artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-artifacts
          path: |
            build/**/*.wasm


  build_webassembly_version:
    name: Build webassembly version (Emscripten)
    runs-on: ubuntu-latest
    container:
        image: emscripten/emsdk:4.0.4
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Build wasm module
        run: |
          mkdir -p build
          cd build
          emcmake cmake ..
          emmake make

      - name: Upload .wasm artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-artifacts
          path: build/bin/**

  linux-build:
    name: Linux build

    runs-on: ubuntu-22.04

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Dependencies (x86)
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y build-essential g++-multilib libc6-dev:i386

      - name: Configure & build
        run: |
          mkdir out
          cd out
          cmake ..
          make

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path:  out/bin/**
          retention-days: 7
